apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-arena
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-arena.intern.dev.nav.no
    - https://tilleggsstonader-arena.dev-fss-pub.nais.io
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-soknad-api
  azure:
    application:
      enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/arena_q1-arena_tilgang_tst
        mountPath: /var/run/secrets/oracle/creds
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: DB_URL
      value: jdbc:oracle:thin:@a01dbfl048.adeo.no:1521/areq01
    - name: DB_USER_PATH
      value: /var/run/secrets/oracle/creds/username
    - name: DB_PASSWORD_PATH
      value: /var/run/secrets/oracle/creds/password

