apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-arena
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-arena.intern.nav.no
    - https://tilleggsstonader-arena.prod-fss-pub.nais.io
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 1Gi # Lik requests som beste praksis
    requests:
      memory: 1Gi
      cpu: 50m
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-sak
          cluster: prod-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  azure:
    application:
      enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/arena-arena_tilgang_tst
        mountPath: /var/run/secrets/oracle/creds
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: DB_URL
      value: jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(CONNECT_TIMEOUT= 15)(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS_LIST=(ADDRESS = (PROTOCOL = TCP)(HOST=a01dbfl049.adeo.no)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST=a01dbfl048.adeo.no)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST=dmv38-scan.adeo.no)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST=dmv34-scan.adeo.no)(PORT = 1521)))(CONNECT_DATA=(SERVICE_NAME = arena_ha)))
    - name: DB_USER_PATH
      value: /var/run/secrets/oracle/creds/username
    - name: DB_PASSWORD_PATH
      value: /var/run/secrets/oracle/creds/password
    - name: TZ
      value: Europe/Oslo
