CREATE TABLE person
(
    SPERRET_DATO                  DATE,           --NOT NULL,
    SPERRET_AV                    VARCHAR2(8),    --NOT NULL,
    FR_KODE                       VARCHAR2(2),    --NOT NULL,
    ER_DOED                       VARCHAR2(1),    --NOT NULL,
    PERSON_ID_STATUS              VARCHAR2(20),
    SPERRET_KOMMENTAR             VARCHAR2(500),  --NOT NULL,
    SPERRET_TIL                   DATE,           --NOT NULL,
    PERSON_ID                     NUMBER,
    FODSELSDATO                   DATE,           --NOT NULL,
    STATUS_DNR                    VARCHAR2(1),
    PERSONNR                      NUMBER(5),      --NOT NULL,
    FODSELSNR                     VARCHAR2(11),   --NOT NULL,
    ETTERNAVN                     VARCHAR2(30),
    FORNAVN                       VARCHAR2(30),
    DATO_FRA                      DATE,
    STATUS_SAMTYKKE               VARCHAR2(1),
    DATO_SAMTYKKE                 DATE,           --NOT NULL,
    VERNEPLIKTKODE                VARCHAR2(5),    --NOT NULL,
    MAALFORM                      VARCHAR2(2),
    LANDKODE_STATSBORGER          VARCHAR2(2),    --NOT NULL,
    KONTONUMMER                   VARCHAR2(11),   --NOT NULL,
    STATUS_BILDISP                VARCHAR2(1),    --NOT NULL,
    FORMIDLINGSGRUPPEKODE         VARCHAR2(5),
    VIKARGRUPPEKODE               VARCHAR2(5),
    KVALIFISERINGSGRUPPEKODE      VARCHAR2(5),
    RETTIGHETSGRUPPEKODE          VARCHAR2(5),
    REG_DATO                      DATE,           --NOT NULL,
    REG_USER                      VARCHAR2(8),    --NOT NULL,
    MOD_DATO                      DATE,           --NOT NULL,
    MOD_USER                      VARCHAR2(8),    --NOT NULL,
    AETATORGENHET                 VARCHAR2(8),    --NOT NULL,
    LONNSLIPP_EPOST               VARCHAR2(1),    --NOT NULL,
    DATO_OVERFORT_AMELDING        DATE,           --NOT NULL,
    DATO_SIST_INAKTIV             DATE,           --NOT NULL,
    BEGRUNNELSE_FORMIDLINGSGRUPPE VARCHAR2(2000), --NOT NULL,
    HOVEDMAALKODE                 VARCHAR2(10),   --NOT NULL,
    BRUKERID_NAV_KONTAKT          VARCHAR2(8)     --NOT NULL
);

CREATE TABLE sak
(
    SAK_ID               NUMBER,       --NOT NULL,
    SAKSKODE             VARCHAR2(10), --NOT NULL,
    REG_DATO             DATE,
    REG_USER             VARCHAR2(8),
    MOD_DATO             DATE,
    MOD_USER             VARCHAR2(8),
    TABELLNAVNALIAS      VARCHAR2(10), --NOT NULL,
    OBJEKT_ID            NUMBER,
    AAR                  NUMBER(4),    --NOT NULL,
    LOPENRSAK            NUMBER(7),    --NOT NULL,
    DATO_AVSLUTTET       DATE,
    SAKSTATUSKODE        VARCHAR2(5),  --NOT NULL,
    ARKIVNOKKEL          VARCHAR2(7),
    AETATENHET_ARKIV     VARCHAR2(8),
    ARKIVHENVISNING      VARCHAR2(255),
    BRUKERID_ANSVARLIG   VARCHAR2(8),
    AETATENHET_ANSVARLIG VARCHAR2(8),
    OBJEKT_KODE          VARCHAR2(10),
    STATUS_ENDRET        DATE,
    PARTISJON            NUMBER(8),
    ER_UTLAND            VARCHAR2(1)   --NOT NULL
);

CREATE TABLE saksforhold
(
    SAKSFORHOLD_ID         NUMBER,
    MAALGRUPPEKODE         VARCHAR2(20), --NOT NULL,
    AKTIVITET_ID           NUMBER,       --NOT NULL,
    SAK_ID                 NUMBER,
    PERSON_ID              NUMBER,
    DATO_FRA               DATE,         --NOT NULL,
    DATO_TIL               DATE,         --NOT NULL,
    KILDE                  VARCHAR2(20),
    REG_DATO               DATE,
    REG_USER               VARCHAR2(8),
    MOD_DATO               DATE,
    MOD_USER               VARCHAR2(8),
    TILTAKDELTAKER_ID      NUMBER(20),   --NOT NULL,
    HIST_TILTAKDELTAKER_ID NUMBER        --NOT NULL
);

CREATE TABLE vedtak
(
    ER_UTLAND              VARCHAR2(1),
    LOPENRSAK              NUMBER(7),
    LOPENRVEDTAK           NUMBER(3),
    RETTIGHETKODE          VARCHAR2(10),
    AKTFASEKODE            VARCHAR2(10),
    BREV_ID                NUMBER,         --NOT NULL,
    TOTALBELOP             NUMBER(8, 2),   --NOT NULL,
    DATO_MOTTATT           DATE,
    VEDTAK_ID_RELATERT     NUMBER,         --NOT NULL,
    AVSNITTLISTEKODE_VALGT VARCHAR2(20),   --NOT NULL,
    PERSON_ID              NUMBER,         --NOT NULL,
    BRUKERID_BESLUTTER     VARCHAR2(8),    --NOT NULL,
    STATUS_SENSITIV        VARCHAR2(1),    --NOT NULL,
    VEDLEGG_BETPLAN        VARCHAR2(1),    --NOT NULL,
    PARTISJON              NUMBER(8),      --NOT NULL,
    OPPSUMMERING_SB2       VARCHAR2(4000), --NOT NULL,
    DATO_UTFORT_DEL1       DATE,           --NOT NULL,
    DATO_UTFORT_DEL2       DATE,           --NOT NULL,
    OVERFORT_NAVI          VARCHAR2(1),    --NOT NULL,
    FRA_DATO               DATE,           --NOT NULL,
    TIL_DATO               DATE,           --NOT NULL,
    SF_OPPFOLGING_ID       NUMBER,         --NOT NULL,
    STATUS_SOSIALDATA      VARCHAR2(1),
    KONTOR_SOSIALDATA      VARCHAR2(8),    --NOT NULL,
    TEKSTVARIANTKODE       VARCHAR2(20),   --NOT NULL,
    VALGT_BESLUTTER        VARCHAR2(8),    --NOT NULL,
    TEKNISK_VEDTAK         VARCHAR2(1),    --NOT NULL,
    DATO_INNSTILT          DATE,           --NOT NULL,
    VEDTAK_ID              NUMBER,
    SAK_ID                 NUMBER,
    VEDTAKSTATUSKODE       VARCHAR2(5),
    VEDTAKTYPEKODE         VARCHAR2(10),
    REG_DATO               DATE,           --NOT NULL,
    REG_USER               VARCHAR2(8),    --NOT NULL,
    MOD_DATO               DATE,           --NOT NULL,
    MOD_USER               VARCHAR2(8),    --NOT NULL,
    UTFALLKODE             VARCHAR2(10),   --NOT NULL,
    BEGRUNNELSE            VARCHAR2(4000), --NOT NULL,
    BRUKERID_ANSVARLIG     VARCHAR2(8),    --NOT NULL,
    AETATENHET_BEHANDLER   VARCHAR2(8),
    AAR                    NUMBER(4)
);

CREATE TABLE taskinstance
(
    ID             NUMBER,
    DESCRIPTION    VARCHAR2(100),
    NOTE           VARCHAR2(2000),
--OPENACTION VARCHAR2(10),
--PRIORITY NUMBER,
--ACCESSED NUMBER,
    DUEDATE        DATE,
--SENTDATE DATE,
--SENDER_ID VARCHAR2(100),
    MAINPROCESS_ID NUMBER,
--CURRENTPROCESS_ID NUMBER,
--COMPLETED NUMBER,
--MAINCONTEXT VARCHAR2(80),
    CASECONTEXT    VARCHAR2(80),
    USERNAME       VARCHAR2(20),
--KONTOR VARCHAR2(8),
--FYLKESNR NUMBER(2),
--OPPRETTET_DATO DATE,
--ER_UTLAND VARCHAR2(1),
    REG_DATO       DATE
--REG_USER VARCHAR2(8),
--MOD_DATO DATE,
--MOD_USER VARCHAR2(8)
);

CREATE TABLE variablebinding
(
    INSTANCEELEMENTID NUMBER,
    VARIABLENAME      VARCHAR2(50),
    STOREDOBJECTTYPE  VARCHAR2(100),
    STOREDOBJECT      VARCHAR2(2000)
);