CREATE TABLE person
(
    SPERRET_DATO                  DATE,           --NOT NULL,
    SPERRET_AV                    VARCHAR2(8),    --NOT NULL,
    FR_KODE                       VARCHAR2(2),    --NOT NULL,
    ER_DOED                       VARCHAR2(1),    --NOT NULL,
    PERSON_ID_STATUS              VARCHAR2(20),
    SPERRET_KOMMENTAR             VARCHAR2(500),  --NOT NULL,
    SPERRET_TIL                   DATE,           --NOT NULL,
    PERSON_ID                     NUMBER,
    FODSELSDATO                   DATE,           --NOT NULL,
    STATUS_DNR                    VARCHAR2(1),
    PERSONNR                      NUMBER(5),      --NOT NULL,
    FODSELSNR                     VARCHAR2(11),   --NOT NULL,
    ETTERNAVN                     VARCHAR2(30),
    FORNAVN                       VARCHAR2(30),
    DATO_FRA                      DATE,
    STATUS_SAMTYKKE               VARCHAR2(1),
    DATO_SAMTYKKE                 DATE,           --NOT NULL,
    VERNEPLIKTKODE                VARCHAR2(5),    --NOT NULL,
    MAALFORM                      VARCHAR2(2),
    LANDKODE_STATSBORGER          VARCHAR2(2),    --NOT NULL,
    KONTONUMMER                   VARCHAR2(11),   --NOT NULL,
    STATUS_BILDISP                VARCHAR2(1),    --NOT NULL,
    FORMIDLINGSGRUPPEKODE         VARCHAR2(5),
    VIKARGRUPPEKODE               VARCHAR2(5),
    KVALIFISERINGSGRUPPEKODE      VARCHAR2(5),
    RETTIGHETSGRUPPEKODE          VARCHAR2(5),
    REG_DATO                      DATE,           --NOT NULL,
    REG_USER                      VARCHAR2(8),    --NOT NULL,
    MOD_DATO                      DATE,           --NOT NULL,
    MOD_USER                      VARCHAR2(8),    --NOT NULL,
    AETATORGENHET                 VARCHAR2(8),    --NOT NULL,
    LONNSLIPP_EPOST               VARCHAR2(1),    --NOT NULL,
    DATO_OVERFORT_AMELDING        DATE,           --NOT NULL,
    DATO_SIST_INAKTIV             DATE,           --NOT NULL,
    BEGRUNNELSE_FORMIDLINGSGRUPPE VARCHAR2(2000), --NOT NULL,
    HOVEDMAALKODE                 VARCHAR2(10),   --NOT NULL,
    BRUKERID_NAV_KONTAKT          VARCHAR2(8)     --NOT NULL
);

CREATE TABLE sak
(
    SAK_ID               NUMBER,       --NOT NULL,
    SAKSKODE             VARCHAR2(10), --NOT NULL,
    REG_DATO             DATE,
    REG_USER             VARCHAR2(8),
    MOD_DATO             DATE,
    MOD_USER             VARCHAR2(8),
    TABELLNAVNALIAS      VARCHAR2(10), --NOT NULL,
    OBJEKT_ID            NUMBER,
    AAR                  NUMBER(4),    --NOT NULL,
    LOPENRSAK            NUMBER(7),    --NOT NULL,
    DATO_AVSLUTTET       DATE,
    SAKSTATUSKODE        VARCHAR2(5),  --NOT NULL,
    ARKIVNOKKEL          VARCHAR2(7),
    AETATENHET_ARKIV     VARCHAR2(8),
    ARKIVHENVISNING      VARCHAR2(255),
    BRUKERID_ANSVARLIG   VARCHAR2(8),
    AETATENHET_ANSVARLIG VARCHAR2(8),
    OBJEKT_KODE          VARCHAR2(10),
    STATUS_ENDRET        DATE,
    PARTISJON            NUMBER(8),
    ER_UTLAND            VARCHAR2(1)   --NOT NULL
);

CREATE TABLE saksforhold
(
    SAKSFORHOLD_ID         NUMBER,
    MAALGRUPPEKODE         VARCHAR2(20), --NOT NULL,
    AKTIVITET_ID           NUMBER,       --NOT NULL,
    SAK_ID                 NUMBER,
    PERSON_ID              NUMBER,
    DATO_FRA               DATE,         --NOT NULL,
    DATO_TIL               DATE,         --NOT NULL,
    KILDE                  VARCHAR2(20),
    REG_DATO               DATE,
    REG_USER               VARCHAR2(8),
    MOD_DATO               DATE,
    MOD_USER               VARCHAR2(8),
    TILTAKDELTAKER_ID      NUMBER(20),   --NOT NULL,
    HIST_TILTAKDELTAKER_ID NUMBER        --NOT NULL
);

CREATE TABLE vedtak
(
    ER_UTLAND              VARCHAR2(1),
    LOPENRSAK              NUMBER(7),
    LOPENRVEDTAK           NUMBER(3),
    RETTIGHETKODE          VARCHAR2(10),
    AKTFASEKODE            VARCHAR2(10),
    BREV_ID                NUMBER,         --NOT NULL,
    TOTALBELOP             NUMBER(8, 2),   --NOT NULL,
    DATO_MOTTATT           DATE,
    VEDTAK_ID_RELATERT     NUMBER,         --NOT NULL,
    AVSNITTLISTEKODE_VALGT VARCHAR2(20),   --NOT NULL,
    PERSON_ID              NUMBER,         --NOT NULL,
    BRUKERID_BESLUTTER     VARCHAR2(8),    --NOT NULL,
    STATUS_SENSITIV        VARCHAR2(1),    --NOT NULL,
    VEDLEGG_BETPLAN        VARCHAR2(1),    --NOT NULL,
    PARTISJON              NUMBER(8),      --NOT NULL,
    OPPSUMMERING_SB2       VARCHAR2(4000), --NOT NULL,
    DATO_UTFORT_DEL1       DATE,           --NOT NULL,
    DATO_UTFORT_DEL2       DATE,           --NOT NULL,
    OVERFORT_NAVI          VARCHAR2(1),    --NOT NULL,
    FRA_DATO               DATE,           --NOT NULL,
    TIL_DATO               DATE,           --NOT NULL,
    SF_OPPFOLGING_ID       NUMBER,         --NOT NULL,
    STATUS_SOSIALDATA      VARCHAR2(1),
    KONTOR_SOSIALDATA      VARCHAR2(8),    --NOT NULL,
    TEKSTVARIANTKODE       VARCHAR2(20),   --NOT NULL,
    VALGT_BESLUTTER        VARCHAR2(8),    --NOT NULL,
    TEKNISK_VEDTAK         VARCHAR2(1),    --NOT NULL,
    DATO_INNSTILT          DATE,           --NOT NULL,
    VEDTAK_ID              NUMBER,
    SAK_ID                 NUMBER,
    VEDTAKSTATUSKODE       VARCHAR2(5),
    VEDTAKTYPEKODE         VARCHAR2(10),
    REG_DATO               DATE,           --NOT NULL,
    REG_USER               VARCHAR2(8),    --NOT NULL,
    MOD_DATO               DATE,           --NOT NULL,
    MOD_USER               VARCHAR2(8),    --NOT NULL,
    UTFALLKODE             VARCHAR2(10),   --NOT NULL,
    BEGRUNNELSE            VARCHAR2(4000), --NOT NULL,
    BRUKERID_ANSVARLIG     VARCHAR2(8),    --NOT NULL,
    AETATENHET_BEHANDLER   VARCHAR2(8),
    AAR                    NUMBER(4)
);

CREATE TABLE taskinstance
(
    ID             NUMBER,
    DESCRIPTION    VARCHAR2(100),
    NOTE           VARCHAR2(2000),
--OPENACTION VARCHAR2(10),
--PRIORITY NUMBER,
--ACCESSED NUMBER,
    DUEDATE        DATE,
--SENTDATE DATE,
--SENDER_ID VARCHAR2(100),
    MAINPROCESS_ID NUMBER,
--CURRENTPROCESS_ID NUMBER,
--COMPLETED NUMBER,
--MAINCONTEXT VARCHAR2(80),
    CASECONTEXT    VARCHAR2(80),
    USERNAME       VARCHAR2(20),
--KONTOR VARCHAR2(8),
--FYLKESNR NUMBER(2),
--OPPRETTET_DATO DATE,
--ER_UTLAND VARCHAR2(1),
    REG_DATO       DATE
--REG_USER VARCHAR2(8),
--MOD_DATO DATE,
--MOD_USER VARCHAR2(8)
);

CREATE TABLE variablebinding
(
    INSTANCEELEMENTID NUMBER,
    VARIABLENAME      VARCHAR2(50),
    STOREDOBJECTTYPE  VARCHAR2(100),
    STOREDOBJECT      VARCHAR2(2000)
);

CREATE TABLE ram_aktivitettype
(
    AKTIVITETKODE            VARCHAR2(10),
    AKTIVITETGRUPPEKODE      VARCHAR2(5),
    AKTIVITETTYPENAVN        VARCHAR2(100),
    DATO_FRA                 DATE,
    DATO_TIL                 DATE,
    DEFINITIONELEMENT_ID     VARCHAR2(100),
    AKTIVITETTYPEBESKRIVELSE VARCHAR2(250),
    STATUS_PERSONAKTIVITET   VARCHAR2(1),
    STATUS_PERSONKORT        VARCHAR2(1),
    STATUS_SENSITIV          VARCHAR2(1),
    AKTORTYPEKODE            VARCHAR2(10),
    TYPE_SJEKKLISTE          VARCHAR2(1),
    STATUS_IA                VARCHAR2(1),
    LENKE_VEILEDERHJULET     VARCHAR2(200),
    STATUS_OPPFOLGING        VARCHAR2(1),
    STATUS_SLETT             VARCHAR2(1),
    STATUS_SF                VARCHAR2(1),
    OBLIG_SJEKKLISTE_JN      VARCHAR2(1),
    STATUS_SJEKK_TILDATO     VARCHAR2(1),
    MAX_ANT_UKER             NUMBER,
    STATUS_LIK_FRA_TIL       VARCHAR2(1),
    MULIG14A                 VARCHAR2(1),
    STATUS_TILLEGGSSTONADER  VARCHAR2(1),
    STATUS_UTDANNING         VARCHAR2(1),
    REG_USER                 VARCHAR2(8),
    REG_DATO                 DATE,
    MOD_USER                 VARCHAR2(8),
    MOD_DATO                 DATE
);

CREATE TABLE aktivitetstatus
(
    AKTIVITETSTATUSKODE VARCHAR2(5),
    AKTIVITETSTATUSNAVN VARCHAR2(30),
    BESKRIVELSE         VARCHAR2(255),
    STATUS_PAGAENDE     VARCHAR2(1)
);

CREATE TABLE ram_aktivitet
(
    AKTIVITETKODE       VARCHAR2(10),
    BESKRIVELSE         VARCHAR2(2000),
--SAKSBEHANDLER	VARCHAR2(8),
--PERSON_ID	NUMBER,
--ARBGIV_ID	NUMBER,
--STATUS_UTSKRIFT	VARCHAR2(10),
--FINANSIERING_BESKRIVELSE	VARCHAR2(2000),
--STATUS_SPEILING	VARCHAR2(1),
--KOMMENTAR_SJEKKLISTE	VARCHAR2(2000),
--FORHAANDSVIS	VARCHAR2(1),
--SAMHANDLER_ID	NUMBER,
--STATUS_SOSIALDATA	VARCHAR2(1),
--KONTOR_SOSIALDATA	VARCHAR2(8),
    AKTIVITET_ID        NUMBER,
    DATO_FRA            DATE,
    DATO_TIL            DATE,
--TASK_ID	NUMBER,
    AKTIVITETSTATUSKODE VARCHAR2(5)--,
--AARSAKVERDIKODE	VARCHAR2(5),
--REG_DATO	DATE,
--REG_USER	VARCHAR2(8),
--MOD_DATO	DATE,
--MOD_USER	VARCHAR2(8),
);

CREATE TABLE vedtaktype
(
    VEDTAKTYPEKODE           VARCHAR2(10),
    VEDTAKTYPENAVN           VARCHAR2(30),
    BESKRIVELSE              VARCHAR2(255),
    DATO_FRA                 DATE,
    DATO_TIL                 DATE,
    REG_USER                 VARCHAR2(8),
    REG_DATO                 DATE,
    MOD_USER                 VARCHAR2(8),
    MOD_DATO                 DATE,
    AVSNITTLISTEKODE_VALGFRI VARCHAR2(20)
);

CREATE TABLE vedtakstatus
(
    VEDTAKSTATUSKODE VARCHAR2(5),
    VEDTAKSTATUSNAVN VARCHAR2(30),
    BESKRIVELSE      VARCHAR2(255)
);

CREATE TABLE vedtakfaktatype
(
    VEDTAKFAKTAKODE      VARCHAR2(10),
    SKJERMBILDETEKST     VARCHAR2(255),
    STATUS_KVOTEBRUK     VARCHAR2(1),
    STATUS_OVERSIKT      VARCHAR2(1),
    VEDTAKFAKTANAVN      VARCHAR2(30),
    BESKRIVELSE          VARCHAR2(255),
    ORACLETYPE           VARCHAR2(10),
    FELTLENGDE           NUMBER(3),
    AVSNITT_ID_LEDETEKST NUMBER,
    REG_DATO             DATE,
    REG_USER             VARCHAR2(8),
    MOD_DATO             DATE,
    MOD_USER             VARCHAR2(8)
);

CREATE TABLE vedtakfakta
(
    VEDTAK_ID       NUMBER,
    VEDTAKFAKTAKODE VARCHAR2(10),
    VEDTAKVERDI     VARCHAR2(2000)--,
    --REG_DATO    DATE,
    --REG_USER    VARCHAR2(8),
    --MOD_DATO    DATE,
    --MOD_USER    VARCHAR2(8),
    --PERSON_ID   NUMBER,
    --PARTISJON   NUMBER(8)
);

CREATE TABLE vilkaarvurdering
(
--    VILKAARVURDERING_ID NUMBER,
--    VEDTAKTYPEKODE      VARCHAR2(10),
    VILKAARKODE       VARCHAR2(10),
    VEDTAK_ID         NUMBER,
--    REG_DATO            DATE,
--    REG_USER            VARCHAR2(8),
--    MOD_DATO            DATE,
--    MOD_USER            VARCHAR2(8),
--    RETTIGHETKODE       VARCHAR2(10),
--    AKTFASEKODE         VARCHAR2(10),
    VILKAARSTATUSKODE VARCHAR2(1),
    VURDERT_AV        VARCHAR2(8)
--    PARTISJON           NUMBER(8),
--    BEGRUNNELSE         CLOB,
--    RETUR_JN            VARCHAR2(1),
--    KOMMENTAR_SB2       VARCHAR2(1000),
--    BEGRUNNELSE_SB2     CLOB,
--    SF_HENDELSE_ID      NUMBER
);

CREATE TABLE vilkaarstatus
(
    VILKAARSTATUSKODE VARCHAR2(1),
    VILKAARSTATUSNAVN VARCHAR2(30)
);

CREATE TABLE vilkaartype
(
    VILKAARKODE         VARCHAR2(10),
    SKJERMBILDETEKST    VARCHAR2(100),
    STATUS_OBLIG        VARCHAR2(1),
    VILKAARNAVN         VARCHAR2(30),
    BESKRIVELSE         VARCHAR2(255),
    URL_HJELPEREFERANSE VARCHAR2(2000),
    REG_DATO            DATE,
    REG_USER            VARCHAR2(8),
    MOD_DATO            DATE,
    MOD_USER            VARCHAR2(8),
    URL_FORSKRIFTTEKST  VARCHAR2(2000),
    URL_LOVTEKST        VARCHAR2(2000),
    URL_RUNDSKRIVTEKST  VARCHAR2(2000),
    DATO_FRA            DATE,
    DATO_TIL            DATE,
    VILKAARREGEL        VARCHAR2(100),
    GRUPPE              VARCHAR2(30)
);

CREATE TABLE spesialutbetaling
(
    --REFERANSE_TOTAL             VARCHAR2(255),
    DATO_FRA                    DATE,
    DATO_TIL                    DATE,
    REG_DATO                    DATE,
    --REG_USER                    VARCHAR2(8),
    MOD_DATO                    DATE,
    --MOD_USER                    VARCHAR2(8),
    --EKSTERNENHET_ID_ALTMOTTAKER NUMBER,
    --FERIEGRUNNLAG               NUMBER(12, 2),
    --FERIEGRUNNLAGKODE           VARCHAR2(10),
    --ORDINAER_YTELSE             VARCHAR2(1),
    --REFERANSE_BILAG             VARCHAR2(25),
    --STATUS_BILAG                VARCHAR2(1),
    --STATUS_ANVIS_BILAG          VARCHAR2(1),
    --PARTISJON                   NUMBER(8),
    --VALGT_UTBET_TYPE            VARCHAR2(20),
    --KATEGORI                    VARCHAR2(50),
    SPESUTBETALING_ID           NUMBER,
    --PERSON_ID                   NUMBER,
    VEDTAK_ID                   NUMBER,
    --LOPENR                      NUMBER(3),
    BRUKER_ID_SAKSBEHANDLER     VARCHAR2(8),
    BRUKER_ID_BESLUTTER         VARCHAR2(8),
    DATO_UTBETALING             DATE,
    BEGRUNNELSE                 VARCHAR2(2000),
    BELOP                       NUMBER(12, 2),
    --BELOPKODE                   VARCHAR2(5),
    --RETTIGHETKODE               VARCHAR2(10),
    --AKTFASEKODE                 VARCHAR2(10),
    VEDTAKSTATUSKODE            VARCHAR2(5)
    --POSTERINGTYPEKODE           VARCHAR2(5),
)