name: Bygg app og kjør tester
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: "Bygger appen, sjekker linting og kjører testene"
    uses: navikt/tilleggsstonader/.github/workflows/java-build-and-test.yml@main
    permissions:
      contents: read